language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
before_script:
  - sudo apt-get update
  - sudo apt-get install -y nodejs
  - npm i -g prettier
  - if [ "$TRAVIS_RUST_VERSION" = "stable" ]; then (rustup component add rustfmt-preview clippy-preview) fi
  - if [ "$TRAVIS_RUST_VERSION" = "stable" ]; then (rustup target add wasm32-unknown-unknown) fi
  - if [ "$TRAVIS_RUST_VERSION" = "stable" ]; then (cargo install -f wasm-bindgen-cli) fi
  - if [ "$TRAVIS_RUST_VERSION" = "stable" ]; then (sudo apt-get install -y firefox) fi
  - if [ "$TRAVIS_RUST_VERSION" = "stable" ]; then (./scripts/install_geckodriver.sh) fi
script:
  - if [ "$TRAVIS_RUST_VERSION" = "stable" ]; then (cargo fmt --all -- --check) fi
  - if [ "$TRAVIS_RUST_VERSION" = "stable" ]; then (cargo clippy -- -D warnings) fi
  - prettier --debug-check -l './**/*.json' './**/*.graphql'
  - cargo test --all
  - cargo build --manifest-path=./graphql_client/examples/github/Cargo.toml
  - cargo build --manifest-path=./graphql_client_cli/Cargo.toml
  - if [ "$TRAVIS_RUST_VERSION" = "stable" ]; then (cd graphql_client_web && cargo test --target wasm32-unknown-unknown) fi
