[workspace]
resolver = "2"
members = [
    "graphql_client",
    "graphql_client_cli",
    "graphql_client_codegen",
    "graphql-introspection-query",
    "graphql_query_derive",

    # Example crates.
    "examples/*",
]

[workspace.package]
version = "0.15.0"
rust-version = "1.66.0"
