[workspace]
resolver = "2"
members = [
    "graphql_client",
    "graphql_client_cli",
    "graphql_client_codegen",
    "graphql-introspection-query",
    "graphql_query_derive",

    # Example crates.
    "examples/*",
]

[workspace.package]
rust-version = "1.64.0"  # also set in CI
