[package]
name = "graphql_client_cli"
description = "The CLI for graphql-client (WIP)"
version = "0.5.1-alpha.0"
authors = ["Tom Houl√© <tom@tomhoule.com>"]
license = "Apache-2.0 OR MIT"

[[bin]]
name = "graphql-client"
path = "src/main.rs"

[dependencies]
failure = "0.1"
reqwest = "^0.9.0"
graphql_client = { version = "0.5.0", path = "../graphql_client" }
graphql_client_codegen = { path = "../graphql_client_codegen/", version = "0.5.0" }
structopt = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
