[package]
name = "graphql_client_codegen"
version = "0.8.0"
authors = ["Tom Houl√© <tom@tomhoule.com>"]
description = "Utility crate for graphql_client"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/graphql-rust/graphql-client"
edition = "2018"

[dependencies]
failure = "0.1"
lazy_static = "1.0"
quote = "0.6"
syn = "0.15.20"
proc-macro2 = { version = "0.4", features = [] }
serde = "^1.0.78"
serde_derive = "1.0"
serde_json = "1.0"
heck = "0.3"
graphql-parser = "0.2.2"
