[package]
name = "graphql_client_codegen"
version = "0.4.0"
authors = ["Tom Houl√© <tom@tomhoule.com>"]
description = "Utility crate for graphql_client"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/tomhoule/graphql-client"

[dependencies]
failure = "0.1"
quote = "^0.6"
syn = "0.14"
proc-macro2 = { version = "0.4", features = [] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
heck = "0.3"
graphql-parser = "0.2"
