[package]
name = "graphql_query_github_example"
version = "0.1.0"
authors = ["Tom Houl√© <tom@tomhoule.com>"]

[dependencies]
failure = "*"
graphql_query = { path = "../.." }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
reqwest = "*"
